"""Wrapper plugin that fakes any `CodingAgentPlugin` for offline tests.

Composition pattern: the bootstrap (when `YAAOF_CODING_AGENT_STUB` is set) walks
the `core.coding_agent` registry and replaces each registered plugin with a
`StubCodingAgentPlugin` wrapping it. From every consumer's perspective, nothing
changes — `core.coding_agent.invoke("claude_code", ...)` returns the same shape;
it just never touches a real CLI or vendor API.

Generic by design: the wrapper has zero knowledge of reviewer-specific findings
or any other domain shape. It synthesizes a minimum-valid instance of whatever
`response_model` the caller passes. That keeps it useful for future plugins
(codex, aider) and future response shapes without per-call customization.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

import structlog
from pydantic import BaseModel

from app.core.coding_agent import (
    AgentInvocationResult,
    AgentInvocationStatus,
    HealthStatus,
    ValidationResult,
)
from app.core.workspace import Workspace

log = structlog.get_logger("testing.stub_coding_agent")


# Per-response-model placeholder synthesizers. New response_models can register
# their own here; falling back to model_validate({}) covers simple shapes.
_PLACEHOLDER_BY_MODEL: dict[str, dict[str, Any]] = {
    "FindingList": {
        "findings": [
            {
                "file": None,
                "line_start": None,
                "line_end": None,
                "severity": "info",
                "title": "Stub finding",
                "body": "Generated by StubCodingAgentPlugin (test mode).",
                "rationale": None,
                "snippet": None,
                "applied_lesson_ids": [],
            }
        ]
    },
    "ReplyResponse": {"body": "[stub] no further comment"},
}


def _placeholder_for(response_model: type[BaseModel]) -> BaseModel:
    """Build a `response_model` instance with minimum valid defaults."""
    name = response_model.__name__
    raw = _PLACEHOLDER_BY_MODEL.get(name, {})
    return response_model.model_validate(raw)


class StubCodingAgentPlugin:
    """Wraps a real `CodingAgentPlugin`; intercepts `invoke()`.

    Constructor takes the wrapped plugin; mirrors its `plugin_id` so the
    registry consumer can't tell the difference. `validate_config` and
    `health_check` pass through unchanged — those probe configuration, not LLM
    behavior, so there's no test reason to fake them.
    """

    def __init__(self, wrapped: Any) -> None:
        self._wrapped = wrapped
        self.plugin_id = wrapped.plugin_id

    async def invoke(
        self,
        workspace: Workspace,
        prompt: str,
        agent_config: dict[str, Any],
        response_model: type[BaseModel],
    ) -> AgentInvocationResult[Any]:
        parsed = _placeholder_for(response_model)
        return AgentInvocationResult(
            status=AgentInvocationStatus.SUCCESS,
            parsed=parsed,
            raw_output=parsed.model_dump_json(),
            raw_stderr="",
            tokens_in=1000,
            tokens_out=200,
            cost_usd=Decimal("0.0050"),
            latency_ms=10,
        )

    async def validate_config(self, agent_config: dict[str, Any]) -> ValidationResult:
        return await self._wrapped.validate_config(agent_config)

    async def health_check(self) -> HealthStatus:
        return HealthStatus(healthy=True, message="stub mode", checked_at=datetime.now(UTC))


def wrap_all_registered_plugins() -> int:
    """Replace every entry in `core.coding_agent._PLUGINS` with a stub wrapping it.

    Returns the count of wrapped plugins. Called from `app/main.py` when
    `YAAOF_CODING_AGENT_STUB` is set; the testing layer is the only thing
    permitted to reach into the registry like this.
    """
    from app.core.coding_agent import _PLUGINS  # noqa: PLC0415 — registry access

    count = 0
    for plugin_id, real in list(_PLUGINS.items()):
        if isinstance(real, StubCodingAgentPlugin):
            continue  # idempotent
        _PLUGINS[plugin_id] = StubCodingAgentPlugin(wrapped=real)
        count += 1
    log.info("stub_coding_agent.wrapped_all", count=count)
    return count
